heat_template_version: 2015-04-30

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

  name:
    type: string

  config:
    type: string

resources:

  install_vhost:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/install-vhost.sh }
      inputs:
        - name: NAME
        - name: CONFIG

  deploy_install_vhost:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: install_vhost }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: https_proxy }
        no_proxy: { get_param: no_proxy }
        NAME: { get_param: name }
        CONFIG: { get_param: config }

outputs:
